name: Rust

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        include:
        - name: windows-latest
          runs-on: windows-latest
          self-hosted: true
          shell: wsl -e wsl-bash {0}
          target: x86_64-pc-windows-msvc
        - name: ubuntu-latest
          runs-on: ubuntu-22.04
          self-hosted: false
          shell: bash
          target: x86_64-unknown-linux-gnu
      fail-fast: false
    name: build / ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      common_args: --target ${{ matrix.target }} --color always --verbose
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      if: ${{ ! matrix.self-hosted }}
    - uses: Swatinem/rust-cache@v2
      if: ${{ ! matrix.self-hosted }}
      with:
        shared-key: ${{ matrix.name }}
    - name: Run clippy
      run: nix develop .#CI -c cargo clippy ${{ env.common_args }} -- -Dwarnings
    - name: Build examples
      run: nix develop .#CI -c cargo build ${{ env.common_args }} --bins
  